package net.andimiller.mcp.core.transport

import scala.concurrent.duration.FiniteDuration
import scala.util.hashing.MurmurHash3

import cats.effect.kernel.Async
import cats.effect.kernel.Deferred
import cats.effect.kernel.Ref
import cats.syntax.all.*

import net.andimiller.mcp.core.protocol.jsonrpc.ErrorCode
import net.andimiller.mcp.core.protocol.jsonrpc.JsonRpcError
import net.andimiller.mcp.core.protocol.jsonrpc.Message
import net.andimiller.mcp.core.protocol.jsonrpc.RequestId

import io.circe.Json

/** Send JSON-RPC requests over a publish callback and await correlated responses.
  *
  * Used by both ends: the server side wraps it as `ServerRequester` (server → client requests like
  * `elicitation/create`), and the client side wraps it as `ClientRequester` (client → server requests like
  * `tools/call`). Both directions share the same correlation logic — only the id-prefix differs so requests originating
  * on each side don't collide.
  */
trait MessageRequester[F[_]]:

  /** Send a request, await the matched response or a timeout. */
  def request(
      method: String,
      params: Option[Json],
      timeout: Option[FiniteDuration] = None
  ): F[Either[JsonRpcError, Json]]

  /** Complete a pending request with the response payload. Called by the inbound message handler. */
  def completeResponse(id: RequestId, result: Either[JsonRpcError, Json]): F[Unit]

object MessageRequester:

  /** Marker error code used when the request times out before a response arrives. */
  val TimeoutErrorCode: Int = -32001

  /** Build a requester that publishes outbound messages via `publish`.
    *
    * IDs are generated by hashing the current realtime timestamp combined with a per-instance counter (so collisions
    * are impossible even if `realTime` resolution is coarse). They are formatted as `"<idPrefix><hex>"`; pass distinct
    * prefixes for each side of the wire (e.g. `"srv-"` and `"cli-"`).
    */
  def create[F[_]: Async](
      publish: Message => F[Unit],
      idPrefix: String
  ): F[MessageRequester[F]] =
    for
      counter <- Ref[F].of(0L)
      pending <- Ref[F].of(Map.empty[RequestId, Deferred[F, Either[JsonRpcError, Json]]])
    yield new MessageRequester[F]:

      def request(
          method: String,
          params: Option[Json],
          timeout: Option[FiniteDuration]
      ): F[Either[JsonRpcError, Json]] =
        for
          id     <- nextId
          d      <- Deferred[F, Either[JsonRpcError, Json]]
          _      <- pending.update(_.updated(id, d))
          result <- Async[F].guarantee(
                      publish(Message.request(id, method, params)) *> awaitWithTimeout(d, timeout),
                      pending.update(_ - id)
                    )
        yield result

      def completeResponse(id: RequestId, result: Either[JsonRpcError, Json]): F[Unit] =
        pending.modify(m => (m - id, m.get(id))).flatMap {
          case Some(d) => d.complete(result).void
          case None    => Async[F].unit
        }

      private val nextId: F[RequestId] =
        for
          t <- Async[F].realTime
          n <- counter.updateAndGet(_ + 1)
          h  = MurmurHash3.stringHash(s"${t.toNanos}-$n")
        yield RequestId.fromString(s"$idPrefix${Integer.toHexString(h)}")

      private def awaitWithTimeout(
          d: Deferred[F, Either[JsonRpcError, Json]],
          timeout: Option[FiniteDuration]
      ): F[Either[JsonRpcError, Json]] =
        timeout match
          case None    => d.get
          case Some(t) =>
            Async[F].race(d.get, Async[F].sleep(t)).map {
              case Left(r)  => r
              case Right(_) => Left(JsonRpcError(TimeoutErrorCode, s"Request timed out after $t", None))
            }

  /** A no-op requester for transports/tests that don't expose request/response. */
  def noop[F[_]: Async](unconfiguredMessage: String = "MessageRequester not configured"): F[MessageRequester[F]] =
    Async[F].pure(new MessageRequester[F]:
      def request(method: String, params: Option[Json], timeout: Option[FiniteDuration]) =
        Async[F].pure(Left(JsonRpcError(ErrorCode.InternalError, unconfiguredMessage, None)))
      def completeResponse(id: RequestId, result: Either[JsonRpcError, Json]) = Async[F].unit)
