package net.andimiller.mcp.golden

import cats.effect.IO
import cats.effect.std.Env
import fs2.Stream
import fs2.io.file.Files
import fs2.io.file.Path
import fs2.text
import io.circe.Encoder
import io.circe.syntax.*
import munit.CatsEffectSuite
import net.andimiller.mcp.core.protocol.*
import net.andimiller.mcp.core.server.Server

abstract class McpGoldenSuite(using sourcecode.File) extends CatsEffectSuite:

  def server: IO[Server[IO]]

  def goldenFileName: String = "mcp.json"

  def goldenHeader: String =
    s"// This file has been autogenerated, don't try to edit it manually\n// To regenerate, delete this file and rerun the associated test: ${getClass.getName}"

  def alwaysOverride: Boolean = false

  def goldenPath: Path =
    val srcFile    = summon[sourcecode.File].value
    val srcTestIdx = srcFile.indexOf("/src/test/")
    if srcTestIdx >= 0 then Path(srcFile.substring(0, srcTestIdx)) / "src" / "test" / "resources"
    else Path("src") / "test" / "resources"

  private case class McpServerSpec(
      info: Implementation,
      capabilities: ServerCapabilities,
      tools: List[ToolDefinition],
      resources: List[ResourceDefinition],
      resourceTemplates: List[ResourceTemplateDefinition],
      prompts: List[PromptDefinition]
  ) derives Encoder.AsObject

  private def extractSpec(): IO[McpServerSpec] =
    server.flatMap { s =>
      for
        tools             <- s.listTools(ListToolsRequest())
        resources         <- s.listResources(ListResourcesRequest())
        resourceTemplates <- s.listResourceTemplates(ListResourceTemplatesRequest())
        prompts           <- s.listPrompts(ListPromptsRequest())
      yield McpServerSpec(
        info = s.info, capabilities = s.capabilities, tools = tools.tools.sortBy(_.name),
        resources = resources.resources.sortBy(_.name),
        resourceTemplates = resourceTemplates.resourceTemplates.sortBy(_.name), prompts = prompts.prompts.sortBy(_.name)
      )
    }

  private def renderSpec(spec: McpServerSpec): String =
    val json = spec.asJson.deepDropNullValues.spaces2SortKeys
    if goldenHeader.nonEmpty then s"$goldenHeader\n$json" else json

  private def writeGoldenFile(filePath: Path, content: String): IO[Unit] =
    Files[IO].createDirectories(goldenPath) >>
      Stream(content).through(text.utf8.encode).through(Files[IO].writeAll(filePath)).compile.drain >>
      Env[IO].get("CI").flatMap {
        case Some(_) => IO(fail("Golden file missing on CI, run tests locally first"))
        case None    => IO.unit
      }

  private def compareGoldenFile(filePath: Path, content: String): IO[Unit] =
    Files[IO].readUtf8(filePath).compile.string.flatMap { existing =>
      IO(assertNoDiff(content, existing))
    }

  test(s"$goldenFileName golden test") {
    for
      spec    <- extractSpec()
      content  = renderSpec(spec)
      filePath = goldenPath / goldenFileName
      exists  <- Files[IO].exists(filePath)
      _       <-
        if !exists || alwaysOverride then writeGoldenFile(filePath, content)
        else compareGoldenFile(filePath, content)
    yield ()
  }
