package net.andimiller.mcp.explorer

object Styles:
  val container = "is-flex is-flex-direction-column full-height"
  val header = "navbar is-dark"
  val headerInput = "input is-small"
  val connectButton = "button is-success is-small"
  val disconnectButton = "button is-danger is-small"
  val main = "is-flex detail-scroll"
  val sidebar = "sidebar is-flex is-flex-direction-column"
  val tabs = "tabs is-boxed is-small"
  val tab = ""
  val activeTab = "is-active"
  val list = "is-flex-grow-1 overflow-y-auto p-2"
  val listItem = "panel-block"
  val selectedItem = "panel-block is-active"
  val detail = "detail-scroll p-4"
  val detailTitle = "title is-4"
  val detailDescription = "subtitle is-6 has-text-grey"
  val section = "mb-4"
  val sectionTitle = "label"
  val textarea = "textarea is-family-monospace"
  val textareaError = "textarea is-family-monospace is-danger"
  val errorText = "help is-danger"
  val resultBox = "box is-family-monospace"
  val buttonRow = "buttons mt-2"
  val formatButton = "button is-info is-small"
  val callButton = "button is-success is-small"
  val resourceContent = "box is-family-monospace"
  val promptMessages = "box p-0"
  val promptMessage = "p-3 border-bottom"
  val promptRole = "has-text-weight-bold mb-1"
  val statusConnected = "has-text-success"
  val statusError = "has-text-danger"
  val statusConnecting = "has-text-warning"
  val emptyState = "has-text-grey-light has-text-centered p-6"
