package net.andimiller.mcp.core.server

import scala.concurrent.duration.FiniteDuration
import scala.util.hashing.MurmurHash3

import cats.effect.kernel.Async
import cats.effect.kernel.Deferred
import cats.effect.kernel.Ref
import cats.syntax.all.*

import net.andimiller.mcp.core.protocol.ClientCapabilities
import net.andimiller.mcp.core.protocol.jsonrpc.ErrorCode
import net.andimiller.mcp.core.protocol.jsonrpc.JsonRpcError
import net.andimiller.mcp.core.protocol.jsonrpc.Message
import net.andimiller.mcp.core.protocol.jsonrpc.RequestId

import io.circe.Json

/** Send server-initiated JSON-RPC requests to the client and await correlated responses.
  *
  * The publish callback is shared with [[NotificationSink]] (both write to the same outbound channel — fs2 Topic on
  * stdio/HTTP). Pending responses are correlated by request ID via a map of [[Deferred]]s; [[completeResponse]] is
  * called from `RequestHandler` when the client sends back a `Message.Response`.
  *
  * Negotiated [[ClientCapabilities]] are stored here so feature-specific clients (e.g. [[ElicitationClient]]) can
  * capability-check before issuing a request.
  */
trait ServerRequester[F[_]]:

  /** Send a request, await the matched response or a timeout. */
  def request(
      method: String,
      params: Option[Json],
      timeout: Option[FiniteDuration] = None
  ): F[Either[JsonRpcError, Json]]

  /** Negotiated client capabilities (None until `initialize` completes). */
  def clientCapabilities: F[Option[ClientCapabilities]]

  /** Complete a pending request with the response payload. Called by the request handler. */
  def completeResponse(id: RequestId, result: Either[JsonRpcError, Json]): F[Unit]

  /** Set the negotiated client capabilities once `initialize` is processed. */
  def setClientCapabilities(caps: ClientCapabilities): F[Unit]

object ServerRequester:

  /** Marker error code used when the request times out before a response arrives. */
  val TimeoutErrorCode: Int = -32001

  /** Build a requester that publishes outbound messages via `publish`.
    *
    * IDs are generated by hashing the current realtime timestamp combined with a per-instance counter (so collisions
    * are impossible even if `realTime` resolution is coarse). They are formatted as `"srv-<hex>"` to avoid collision
    * with client-issued IDs.
    */
  def create[F[_]: Async](publish: Message => F[Unit]): F[ServerRequester[F]] =
    for
      counter <- Ref[F].of(0L)
      caps    <- Ref[F].of(Option.empty[ClientCapabilities])
      pending <- Ref[F].of(Map.empty[RequestId, Deferred[F, Either[JsonRpcError, Json]]])
    yield new ServerRequester[F]:

      def clientCapabilities: F[Option[ClientCapabilities]] = caps.get

      def setClientCapabilities(c: ClientCapabilities): F[Unit] = caps.set(Some(c))

      def request(
          method: String,
          params: Option[Json],
          timeout: Option[FiniteDuration]
      ): F[Either[JsonRpcError, Json]] =
        for
          id     <- nextId
          d      <- Deferred[F, Either[JsonRpcError, Json]]
          _      <- pending.update(_.updated(id, d))
          result <- Async[F].guarantee(
                      publish(Message.request(id, method, params)) *> awaitWithTimeout(d, timeout),
                      pending.update(_ - id)
                    )
        yield result

      def completeResponse(id: RequestId, result: Either[JsonRpcError, Json]): F[Unit] =
        pending.modify(m => (m - id, m.get(id))).flatMap {
          case Some(d) => d.complete(result).void
          case None    => Async[F].unit
        }

      private val nextId: F[RequestId] =
        for
          t <- Async[F].realTime
          n <- counter.updateAndGet(_ + 1)
          h  = MurmurHash3.stringHash(s"${t.toNanos}-$n")
        yield RequestId.fromString(s"srv-${Integer.toHexString(h)}")

      private def awaitWithTimeout(
          d: Deferred[F, Either[JsonRpcError, Json]],
          timeout: Option[FiniteDuration]
      ): F[Either[JsonRpcError, Json]] =
        timeout match
          case None    => d.get
          case Some(t) =>
            Async[F].race(d.get, Async[F].sleep(t)).map {
              case Left(r)  => r
              case Right(_) => Left(JsonRpcError(TimeoutErrorCode, s"Request timed out after $t", None))
            }

  /** A no-op requester for transports/tests that don't expose server-initiated requests. */
  def noop[F[_]: Async]: F[ServerRequester[F]] =
    Ref[F].of(Option.empty[ClientCapabilities]).map { caps =>
      new ServerRequester[F]:
        def request(method: String, params: Option[Json], timeout: Option[FiniteDuration]) =
          Async[F].pure(Left(JsonRpcError(ErrorCode.InternalError, "ServerRequester not configured", None)))
        def clientCapabilities                                                  = caps.get
        def completeResponse(id: RequestId, result: Either[JsonRpcError, Json]) = Async[F].unit
        def setClientCapabilities(c: ClientCapabilities)                        = caps.set(Some(c))
    }
